# This is a basic workflow to help you get started with Actions

name: CI-CD-pipeline-for-java-app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
     # - run: mkdir staging && cp target/*.jar staging
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
          
      - name: Build & Push Image
        id: build-image
          #env:
      
      #                 DOCKER_BUILDKIT: 1

        run: |
                    git_hash=$(git rev-parse --short "$GITHUB_SHA")
                    docker build -t achinoam84/test:$git_hash -t achinoam84/test:github .
                    docker push achinoam84/test:$git_hash
                    docker push achinoam84/test:github
                   # echo "::set-output name=image::$achinoam84/test:GITHUB_SHA"
                   
                   
      - name: "Install kubectl"
        uses: azure/setup-kubectl@v1

      - name: Setup Huawei Cloud K8S environment
  env:
        hostname: 'cce.ru-moscow-1.hc.sbercloud.ru'
          
        uses: huaweicloud/cce-cluster-credentials@v1
        with:
            region: "${{ secrets.REGION }}"
            access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
            access-key-secret: "${{ secrets.SECRET_ACCESS_KEY }}"
            project-id: "${{ secrets.PROJECT_ID }}"
            cluster-id: "${{ secrets.CLUSTER_ID }}"
            
      - name: Run the Docker image
        run: |-
            kubectl config use-context external # HuaweiCloud specific !
            kubectl run super_app --rm -i --image achinoam84/test:github --restart=Never --tty=false
     


      
     # - uses: actions/upload-artifact@v2
      #  with:
       #   name: Package
        #  path: staging
   
      #- name: Upload image
      #  uses: ishworkh/docker-image-artifact-upload@v1
       # with:
        #  image: "achinoam84/test:github"
          
      
